package: java-installer
version: 2.17
maintainer: rednoah@filebot.net

title: Java Installer
description: Java Installer will help you install and update Java. Supported platforms include armv7l, aarch64, i586 and x86_64 models. During the install, this package will download the latest OpenJDK binaries (180 MB) for your platform. This may take a while.

product: OpenJDK
release: 21.0.9

adoptium_release: 21.0.9+10-LTS
liberica_release: 21.0.9+11
openjfx_release: 21.0.9


# NOTES
# * JDK 25 drops support for 32-bit x86 and 32-bit ARM platforms
# * JDK 25 builds no longer include jmods (which are now provided as a separate package)
# * Adoptium JDK 25 does not yet support Windows (arm64)
