#!/bin/sh

PKG_LOG="$SYNOPKG_PKGDEST/install-jdk.log"


# set working dir
cd "$SYNOPKG_PKGDEST"

# fetch JDK
"$SYNOPKG_PKGDEST/get-java.sh" install jdk 2>&1 | tee "$PKG_LOG"

# make sure that `java` is working
if [ -x "/usr/local/java/bin/java" ]; then
	# display success message
	"/usr/local/java/bin/java" -version 2>&1 | tee "$SYNOPKG_TEMP_LOGFILE"
else
	# display error message
	echo "Ooops, something went wrong... View Log for details." | tee "$SYNOPKG_TEMP_LOGFILE"
fi


# return successfully
exit 0
