#!/bin/sh


# remove symlinks
rm "/usr/local/bin/java"
rm "/usr/local/java"


# remove /etc/profile additions
SYS_PROFILE="/etc/profile"
COMMENT="# added by Unofficial Java Installer"

sed -i "/${COMMENT}/d" "$SYS_PROFILE"


# return successfully
exit 0
