#!/bin/sh

PKG_LOG="$SYNOPKG_PKGDEST/install-jdk.log"
SYS_PROFILE="/etc/profile"
COMMENT="# added by Unofficial Java Installer"


case "$1" in
	start)
		if [ `grep -c "$COMMENT" $SYS_PROFILE` == "0" ]; then
			if [ -x "/usr/local/java/bin/java" ]; then
				echo "Add environment variables to $SYS_PROFILE" >> "$PKG_LOG"

				# add environment variables to /etc/profile
				echo "export JAVA_HOME=/usr/local/java    ${COMMENT}" >> "$SYS_PROFILE"

				# set -Xmx to 0.7 of physical memory
				JAVA_MAX_MEMORY=`free | awk -vm=1024 -vp=0.7 '/Mem:/ {printf "-Xmx%dm", ($2*p)/m; exit}'`
				echo "export JAVA_OPTS=\"${JAVA_MAX_MEMORY}\"         ${COMMENT}" >> "$SYS_PROFILE"

				# set UTF-8 as sun.jnu.encoding
				echo "export LANG=en_US.utf8              ${COMMENT}" >> "$SYS_PROFILE"
			fi
		fi
		exit 0
	;;

	stop)
		exit 0
	;;

	status)
		exit 0
	;;

	log)
		echo "$PKG_LOG"
		exit 0
	;;

	*)
		exit 1
	;;
esac
